const lessonTitle = "郑人买履";

const lessonData = [
    // ===== 文言文 =====
    ["郑", "zhèng", "Zheng", "Zheng", "郑国"],
    ["人", "rén", "person", "orang", "有个"],
    ["有", "yǒu", "there was", "ada", "有"],
    ["欲", "yù", "want to", "mahu", "想要"],
    ["买", "mǎi", "buy", "membeli", "买"],
    ["履", "lǚ", "shoes", "kasut", "鞋子"],
    ["者", "zhě", "person", "orang", "的人"],
    ["，", "", "", "", ""],
    ["先", "xiān", "first", "pertama", "先"],
    ["自", "zì", "himself", "dirinya", "自己"],
    ["度", "duó", "measure", "mengukur", "量"],
    ["其", "qí", "his", "dia punya", "他的"],
    ["足", "zú", "feet", "kaki", "脚"],
    ["，", "", "", "", ""],
    ["而", "ér", "then", "kemudian", "然后"],
    ["置", "zhì", "put", "meletakkan", "放"],
    ["之", "zhī", "it", "ia", "它"],
    ["其", "qí", "his", "dia punya", "他的"],
    ["坐", "zuò", "seat", "tempat duduk", "座位"],
    ["。", "", "", "", ""],
    ["至", "zhì", "when", "apabila", "等到"],
    ["之", "zhī", "go to", "pergi ke", "到"],
    ["市", "shì", "market", "pasar", "集市"],
    ["，", "", "", "", ""],
    ["而", "ér", "but", "tetapi", "却"],
    ["忘", "wàng", "forget", "lupa", "忘记"],
    ["操", "cāo", "take", "membawa", "带"],
    ["之", "zhī", "it", "ia", "它"],
    ["。", "", "", "", ""],
    ["已", "yǐ", "after", "selepas", "已经"],
    ["得", "dé", "got", "mendapat", "找到"],
    ["履", "lǚ", "shoes", "kasut", "鞋子"],
    ["，", "", "", "", ""],
    ["乃", "nǎi", "then", "lalu", "就"],
    ["曰", "yuē", "said", "berkata", "说"],
    ["：", "", "", "", ""],
    ["“", "", "", "", ""],
    ["吾", "wú", "I", "saya", "我"],
    ["忘", "wàng", "forget", "lupa", "忘记"],
    ["持", "chí", "carry", "membawa", "带"],
    ["度", "dù", "measurement", "ukuran", "量好的尺码"],
    ["。”", "", "", "", ""],
    ["反", "fǎn", "return", "kembali", "返回"],
    ["归", "guī", "go back", "pulang", "回去"],
    ["取", "qǔ", "fetch", "mengambil", "取"],
    ["之", "zhī", "it", "ia", "它"],
    ["。", "", "", "", ""],
    ["及", "jí", "when", "apabila", "等到"],
    ["反", "fǎn", "return", "kembali", "返回"],
    ["，", "", "", "", ""],
    ["市", "shì", "market", "pasar", "集市"],
    ["罢", "bà", "closed", "tutup", "散了"],
    ["，", "", "", "", ""],
    ["遂", "suì", "finally", "akhirnya", "最终"],
    ["不得", "bù dé", "could not get", "tidak dapat", "没能买到"],
    ["履", "lǚ", "shoes", "kasut", "鞋子"],
    ["。", "", "", "", ""],
    ["人", "rén", "Someone", "Seseorang", "有人"],
    ["曰", "yuē", "said", "berkata", "说"],
    ["：", "", "", "", ""],
    ["“", "", "", "", ""],
    ["何", "hé", "why", "kenapa", "为什么"],
    ["不", "bù", "not", "tidak", "不"],
    ["试", "shì", "try", "cuba", "试"],
    ["之", "zhī", "it", "ia", "它"],
    ["以", "yǐ", "with", "dengan", "用"],
    ["足", "zú", "feet", "kaki", "脚"],
    ["？”", "", "", "", ""],
    ["曰", "yuē", "He said", "Dia berkata", "他说"],
    ["：", "", "", "", ""],
    ["“", "", "", "", ""],
    ["宁", "nìng", "would rather", "lebih baik", "宁可"],
    ["信", "xìn", "trust", "percaya", "相信"],
    ["度", "dù", "measurement", "ukuran", "量好的尺码"],
    ["，", "", "", "", ""],
    ["无", "wú", "not", "tidak", "不"],
    ["自", "zì", "oneself", "diri sendiri", "自己"],
    ["信", "xìn", "trust", "percaya", "相信"],
    ["也", "yě", "particle", "lah", "了"],
    ["。”", "", "", "", ""],

    ["\n", "", "", ""], // 👈 段落结束 → 出处

    ["（", "", "", "", ""],
    ["《", "", "", "", ""],
    ["韩非子", "hán fēi zǐ", "Han Feizi", "Han Feizi", "韩非子"],
    ["》", "", "", "", ""],
    ["，", "", "", "", ""],
    ["有", "yǒu", "with", "ada", "有"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai", "改动"],
    ["）", "", "", "", ""]
];
